# Generated by Django 4.1.7 on 2024-03-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0004_applicationuser_cnic_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='private_key',
            field=models.CharField(default='asas', max_length=60),
            preserve_default=False,
        ),
    ]
