# Generated by Django 4.1.7 on 2024-03-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0005_applicationuser_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastMessage', models.CharField(max_length=255)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_as_buyer', to='backendApplication.applicationuser')),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_as_seller', to='backendApplication.applicationuser')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ChatRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApplication.chat')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApplication.applicationuser')),
            ],
        ),
    ]
