# Generated by Django 4.1.7 on 2024-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0006_chat_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='profile_pic',
            field=models.CharField(default='Default.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
