# Generated by Django 4.1.7 on 2024-03-17 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0008_chat_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 12, 38, 19, 205185, tzinfo=datetime.timezone.utc)),
        ),
    ]
