# Generated by Django 4.1.7 on 2024-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0009_alter_chat_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
