# Generated by Django 4.1.7 on 2024-03-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0010_alter_chat_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='Status',
            field=models.CharField(default='Viewed', max_length=20),
            preserve_default=False,
        ),
    ]
