# Generated by Django 4.1.7 on 2024-03-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0013_chat_unviewperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='unviewPerson',
        ),
    ]
