# Generated by Django 4.1.7 on 2024-03-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0014_remove_chat_unviewperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unviewPerson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backendApplication.applicationuser'),
            preserve_default=False,
        ),
    ]
