# Generated by Django 4.1.7 on 2024-03-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0015_chat_unviewperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueType', models.CharField(max_length=50)),
                ('IssueDate', models.CharField(max_length=50)),
                ('IssueDetails', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('SubmitBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApplication.applicationuser')),
            ],
        ),
    ]
