# Generated by Django 4.1.7 on 2024-03-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0016_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ResolveStatus',
            field=models.CharField(choices=[('Unseen', 'Unseen'), ('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Unseen', max_length=20),
        ),
    ]
