# Generated by Django 4.1.7 on 2024-03-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0017_issue_resolvestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='Feedback',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
    ]
