# Generated by Django 4.1.7 on 2024-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0020_applicationuser_langitude_applicationuser_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='location',
            field=models.CharField(default='Lahore', max_length=255),
            preserve_default=False,
        ),
    ]
