# Generated by Django 4.1.7 on 2024-04-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0021_applicationuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendApplication.applicationuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
    ]
