# Generated by Django 4.1.7 on 2024-04-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0022_property_location_property_seller_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyImages',
            new_name='PropertyImage',
        ),
    ]
