# Generated by Django 4.1.7 on 2024-04-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0024_rename_propertytype_property_listingtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='propertType',
        ),
        migrations.RemoveField(
            model_name='property',
            name='views',
        ),
        migrations.AddField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('Appartment', 'Appartment'), ('House', 'Hosue'), ('Hostel', 'Hostel'), ('N/A', 'N/A'), ('Room', 'Room')], default='N/A', max_length=20),
        ),
    ]
