# Generated by Django 4.1.7 on 2024-04-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0025_remove_property_properttype_remove_property_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('Appartment', 'Appartment'), ('Hostel', 'Hostel'), ('N/A', 'N/A'), ('House', 'Hosue'), ('Room', 'Room')], default='N/A', max_length=20),
        ),
    ]
