# Generated by Django 4.1.7 on 2024-05-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0026_property_views_alter_property_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='abstractLocation',
            field=models.CharField(default='Qalandar Pura, Lahore District, Punjab', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('Appartment', 'Appartment'), ('N/A', 'N/A'), ('House', 'Hosue'), ('Room', 'Room'), ('Hostel', 'Hostel')], default='N/A', max_length=20),
        ),
    ]
