# Generated by Django 4.1.7 on 2024-05-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0027_property_abstractlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('Room', 'Room'), ('N/A', 'N/A'), ('House', 'Hosue'), ('Appartment', 'Appartment'), ('Hostel', 'Hostel')], default='N/A', max_length=20),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApplication.property')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApplication.applicationuser')),
            ],
        ),
    ]
