# Generated by Django 4.1.7 on 2024-05-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0028_alter_property_propertytype_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='seller',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('House', 'Hosue'), ('Room', 'Room'), ('Appartment', 'Appartment'), ('N/A', 'N/A'), ('Hostel', 'Hostel')], default='N/A', max_length=20),
        ),
    ]
