# Generated by Django 4.1.7 on 2024-05-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0030_alter_property_propertytype_propertyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('House', 'Hosue'), ('Hostel', 'Hostel'), ('Appartment', 'Appartment'), ('Room', 'Room'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
    ]
