# Generated by Django 4.1.7 on 2024-05-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0032_chatmessage_type_alter_property_propertytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('House', 'Hosue'), ('Hostel', 'Hostel'), ('Appartment', 'Appartment'), ('Room', 'Room'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('propertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApplication.property')),
                ('reviewPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApplication.applicationuser')),
            ],
        ),
    ]
