# Generated by Django 4.1.7 on 2024-05-23 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0033_alter_property_propertytype_propertyreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('Hostel', 'Hostel'), ('House', 'Hosue'), ('Room', 'Room'), ('N/A', 'N/A'), ('Appartment', 'Appartment')], default='N/A', max_length=20),
        ),
    ]
