# Generated by Django 4.1.7 on 2024-05-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0034_property_timestamp_alter_property_propertytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('Room', 'Room'), ('Appartment', 'Appartment'), ('House', 'Hosue'), ('N/A', 'N/A'), ('Hostel', 'Hostel')], default='N/A', max_length=20),
        ),
    ]
