# Generated by Django 4.1.7 on 2024-05-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0035_alter_property_propertytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('Hostel', 'Hostel'), ('Appartment', 'Appartment'), ('House', 'Hosue'), ('Room', 'Room'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
    ]
