# Generated by Django 4.1.7 on 2024-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0037_favourite_timestamp_alter_property_propertytype_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('N/A', 'N/A'), ('House', 'House'), ('Room', 'Room'), ('Appartment', 'Appartment'), ('Hostel', 'Hostel')], default='N/A', max_length=20),
        ),
    ]
