# Generated by Django 4.1.7 on 2024-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0039_alter_property_propertytype_propertyvirtualvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='account_verification',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Suspended', 'Suspended')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('Appartment', 'Appartment'), ('House', 'House'), ('N/A', 'N/A'), ('Hostel', 'Hostel'), ('Room', 'Room')], default='N/A', max_length=20),
        ),
    ]
