# Generated by Django 4.1.7 on 2024-06-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApplication', '0041_alter_property_propertytype_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Appartment', 'Appartment'), ('Room', 'Room'), ('House', 'House'), ('Hostel', 'Hostel')], default='N/A', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fileLocation', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('propertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApplication.property')),
            ],
        ),
    ]
